let users = [
    {
        name: 'hubertus',
        email: 'test123@test.de',
        password: 'test123',
        contacts: [
            {
                name: "Sarah Testling",
                phone: "067 304 08 50",
                email: "123test@test.de",
                id: "1702909750145",
                bgColour: "#34495e",
            },
            {
                name: "Kevin Testling",
                phone: "067 304 08 15",
                email: "123test@testling.de",
                id: "1702909750146",
                bgColour: "#34495e",
            },
        ],
        tasks: [
            {
                assignedUsers: [],
                category: {
                    colour: "#1FD7C1",
                    name: "Project and Task Management"
                },
                date: "2023-12-30T00:00:00.000Z",
                description: "Autogenerated updated",
                prio: 2,
                subtasks: [
                    {
                        0: 1703155545530,
                        1: "ffffffffffff",
                        2: true,
                    },
                    {
                        0: 1703155547976,
                        1: "gggg",
                        2: true
                    },
                    {
                        0: 1703155547976,
                        1: "gggg",
                        2: true
                    },
                    {
                        0: 1703158409224,
                        1: "jjj",
                        2: true
                    }
                ],
                taskID: 1703155553194,
                taskStatus: 0,
                title: "Autogenerated"
            }
        ]
    },
];
